export default [
  {
    nameAirport: "Acadiana Regional",
    codeIataAirport: "ARA",
    codeIcaoAirport: "KARA",
    nameTranslations:
      "Regionaler Flughafen Acadiana,Acadiana Regional,??? ?????????",
    latitudeAirport: "30.037779",
    longitudeAirport: "-91.88389",
    timezone: "America/Chicago",
    GMT: "-6",
    phone: "",
    nameCountry: "United States",
    codeIso2Country: "US",
    codeIataCity: "ARA",
    distance: "8.055864425769563"
  },
  {
    nameAirport: "Lafayette Regional",
    codeIataAirport: "LFT",
    codeIcaoAirport: "KLFT",
    nameTranslations:
      "Lafayette Regional,Lafayette Regional,Lafayette Regional,Lafayette Regional,Lafayette Regional,??????????????,?????",
    latitudeAirport: "30.20851",
    longitudeAirport: "-91.99327",
    timezone: "America/Chicago",
    GMT: "-6",
    phone: "",
    nameCountry: "United States",
    codeIso2Country: "US",
    codeIataCity: "LFT",
    distance: "26.34407370514819"
  },
  {
    nameAirport: "Williams Memorial",
    codeIataAirport: "PTN",
    codeIcaoAirport: "KPTN",
    nameTranslations: "Williams Memorial,Williams Memorial Havaliman?,?????",
    latitudeAirport: "29.708332",
    longitudeAirport: "-91.3375",
    timezone: "America/Chicago",
    GMT: "-6",
    phone: "",
    nameCountry: "United States",
    codeIso2Country: "US",
    codeIataCity: "PTN",
    distance: "58.03281659284613"
  },
  {
    nameAirport: "St Landry Parish",
    codeIataAirport: "OPL",
    codeIcaoAirport: "KOPL",
    nameTranslations: "St Landry Parish,???????",
    latitudeAirport: "30.533333",
    longitudeAirport: "-92.083336",
    timezone: "America/Chicago",
    GMT: "-6",
    phone: "",
    nameCountry: "United States",
    codeIso2Country: "US",
    codeIataCity: "OPL",
    distance: "61.22566969190781"
  },
  {
    nameAirport: "Downtown",
    codeIataAirport: "EBR",
    codeIcaoAirport: "",
    nameTranslations: "Downtown,??????",
    latitudeAirport: "30.45",
    longitudeAirport: "-91.183334",
    timezone: "America/Chicago",
    GMT: "-6",
    phone: "",
    nameCountry: "United States",
    codeIso2Country: "US",
    codeIataCity: "BTR",
    distance: "74.83212283449961"
  },
  {
    nameAirport: "Eunice",
    codeIataAirport: "UCE",
    codeIcaoAirport: "",
    nameTranslations: "Eunice,?????",
    latitudeAirport: "30.5",
    longitudeAirport: "-92.416664",
    timezone: "America/Chicago",
    GMT: "-6",
    phone: "",
    nameCountry: "United States",
    codeIso2Country: "US",
    codeIataCity: "UCE",
    distance: "78.27867890292045"
  },
  {
    nameAirport: "Ryan",
    codeIataAirport: "BTR",
    codeIcaoAirport: "KBTR",
    nameTranslations:
      "Baton Rouge,Ryan,Ryan,Ryan,Ryan,???????? / ????????,??????",
    latitudeAirport: "30.532537",
    longitudeAirport: "-91.156906",
    timezone: "America/Chicago",
    GMT: "-6",
    phone: "",
    nameCountry: "United States",
    codeIso2Country: "US",
    codeIataCity: "BTR",
    distance: "82.6254775222571"
  }
];
