export default {
  totalResultsCount: 11902271,
  geonames: [
    {
      adminCode1: "LA",
      lng: "-91.80039",
      geonameId: 4321690,
      toponymName: "Daspit",
      countryId: "6252001",
      fcl: "P",
      population: 0,
      countryCode: "US",
      name: "Daspit",
      fclName: "city, village,...",
      adminCodes1: { ISO3166_2: "LA" },
      countryName: "United States",
      fcodeName: "populated place",
      adminName1: "Louisiana",
      lat: "30.04076",
      fcode: "PPL"
    },
    {
      adminCode1: "LA",
      lng: "-90.73593",
      geonameId: 4321691,
      toponymName: "Davis Branch",
      countryId: "6252001",
      fcl: "H",
      population: 0,
      countryCode: "US",
      name: "Davis Branch",
      fclName: "stream, lake, ...",
      adminCodes1: { ISO3166_2: "LA" },
      countryName: "United States",
      fcodeName: "stream",
      adminName1: "Louisiana",
      lat: "30.71657",
      fcode: "STM"
    },
    {
      adminCode1: "LA",
      lng: "-92.06958",
      geonameId: 4321692,
      toponymName: "Davis Bend",
      countryId: "6252001",
      fcl: "H",
      population: 0,
      countryCode: "US",
      name: "Davis Bend",
      fclName: "stream, lake, ...",
      adminCodes1: { ISO3166_2: "LA" },
      countryName: "United States",
      fcodeName: "stream bend",
      adminName1: "Louisiana",
      lat: "32.73347",
      fcode: "STMB"
    },
    {
      adminCode1: "LA",
      lng: "-90.33064",
      geonameId: 4321693,
      toponymName: "Davis Branch",
      countryId: "6252001",
      fcl: "H",
      population: 0,
      countryCode: "US",
      name: "Davis Branch",
      fclName: "stream, lake, ...",
      adminCodes1: { ISO3166_2: "LA" },
      countryName: "United States",
      fcodeName: "stream",
      adminName1: "Louisiana",
      lat: "30.76269",
      fcode: "STM"
    },
    {
      adminCode1: "LA",
      lng: "-90.46509",
      geonameId: 4321694,
      toponymName: "Davis Branch",
      countryId: "6252001",
      fcl: "H",
      population: 0,
      countryCode: "US",
      name: "Davis Branch",
      fclName: "stream, lake, ...",
      adminCodes1: { ISO3166_2: "LA" },
      countryName: "United States",
      fcodeName: "stream",
      adminName1: "Louisiana",
      lat: "30.62436",
      fcode: "STM"
    }
  ]
};
